# Generated by Django 6.0.2 on 2026-02-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='account_user_profile',
        ),
    ]
