# Generated by Django 6.0.2 on 2026-03-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_complete',
            field=models.BooleanField(default=False),
        ),
    ]
